In [77]:
import pandas as pd
import numpy as np

In [2]:
import nltk

In [3]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [4]:
from nltk.corpus import brown

In [5]:
print(brown.categories())
print(len(brown.categories()))

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [6]:
data=brown.sents(categories="adventure")

In [7]:
print(data)
print(len(data))

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]
4637


In [8]:
print(data[1])
print(" ".join(data[1]))

['He', 'was', 'well', 'rid', 'of', 'her', '.']
He was well rid of her .


## Tokenization and stopwords removal

In [9]:
document="I was never ready for any of this . I thought you loved me . Well you are a looser,Who want's to be with a looser ."
sentance ="Probably you are right,Have a nice life ahead?"

In [10]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [11]:
sents=sent_tokenize(document)
print(sents)

['I was never ready for any of this .', 'I thought you loved me .', "Well you are a looser,Who want's to be with a looser ."]


In [15]:
print(sentance.split())

['Probably', 'you', 'are', 'right,Have', 'a', 'nice', 'life', 'ahead?']


In [16]:
words=word_tokenize(sentance)
print(words)

['Probably', 'you', 'are', 'right', ',', 'Have', 'a', 'nice', 'life', 'ahead', '?']


### stopwords
- most commonly used word in english

In [12]:
from nltk.corpus import stopwords

In [13]:
sw=set(stopwords.words("english"))
print(sw)

{'other', 'some', 's', "you'll", 'll', 'yourself', 'o', 'isn', 'being', 'your', 'from', 'is', 'mightn', "you've", 'doesn', 'are', "weren't", 'him', 'am', 'each', 'the', "didn't", 'because', 'will', "hasn't", 'and', 'he', 'were', 'myself', "doesn't", "that'll", 'very', 'my', 'up', 'over', 'whom', 'she', 'by', 'between', 'yours', "needn't", 'was', 'a', 'has', 'their', 'on', "mightn't", 'this', 'what', 'then', 'down', 'during', 'more', 'where', 'you', 'same', 'wasn', 'those', 'ours', 'our', "aren't", 'having', 'they', 'under', 'hasn', 'themselves', 'both', 'at', "it's", 'hadn', 'we', 'with', 'into', 'me', 'why', 'there', 'as', 't', 'his', 'ain', 'aren', 'haven', "mustn't", 'weren', 'shan', 'which', 'nor', 'theirs', 'himself', 'd', 're', 'it', 'her', 'did', 'about', 'had', 'be', 'for', "wouldn't", 'won', "hadn't", 'who', 'again', 'don', 'now', 'have', "she's", "shouldn't", 'above', 'doing', 'i', 'to', "you're", 'does', 'didn', 'no', 'ourselves', 'can', 'further', 'herself', 'so', 'these', 

In [14]:
def remove_stopwords(text,stopwords):
    useful_words=[w for w in text if w not in stopwords]
    return useful_words

In [17]:
remove_stopwords(words,sw)

['Probably', 'right', ',', 'Have', 'nice', 'life', 'ahead', '?']

### Tokenize using regular Expression

In [18]:
from nltk.tokenize import RegexpTokenizer

In [19]:
example="This is the 1,2,3 sample sentence"
tokenizer=RegexpTokenizer("[a-zA-Z]+")
useful=tokenizer.tokenize(example)
print(useful)

['This', 'is', 'the', 'sample', 'sentence']


### Stemming
- Transform particular words into its base form
- Example:- Jumping->Jump,laughs->laugh

In [20]:
from nltk.stem.snowball import SnowballStemmer,PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [21]:
ps=PorterStemmer()

In [22]:
ps.stem("Jumping")

'jump'

In [23]:
ps.stem("laughed")

'laugh'

## Building a Vocabulary and Vectorization

In [24]:
corpus=["Indian cricket team is the best cricket team in the world.Recently the team proves its dominance over the best in the word Australia by 5-0.",
       
        "Due to our corrupted leaders our country capital is detoriating day by day",
       
        "Indian movies are a total bullshit except some"
       ]

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv=CountVectorizer()

In [27]:
vectorized_corpus=cv.fit_transform(corpus)

In [28]:
vectorized_corpus=vectorized_corpus.toarray()

In [29]:
print(vectorized_corpus)

[[0 1 2 0 1 0 0 0 2 0 0 1 0 0 2 1 1 1 0 0 0 1 1 1 0 3 5 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 2 1 0 1 0 0 0 1 0 1 0 2 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]]


In [34]:
len(vectorized_corpus[0])

31

In [30]:
print(cv.vocabulary_)

{'indian': 15, 'cricket': 8, 'team': 25, 'is': 16, 'the': 26, 'best': 2, 'in': 14, 'world': 30, 'recently': 23, 'proves': 22, 'its': 17, 'dominance': 11, 'over': 21, 'word': 29, 'australia': 1, 'by': 4, 'due': 12, 'to': 27, 'our': 20, 'corrupted': 6, 'leaders': 18, 'country': 7, 'capital': 5, 'detoriating': 10, 'day': 9, 'movies': 19, 'are': 0, 'total': 28, 'bullshit': 3, 'except': 13, 'some': 24}


In [31]:
cv.inverse_transform(vectorized_corpus[1])

[array(['by', 'capital', 'corrupted', 'country', 'day', 'detoriating',
        'due', 'is', 'leaders', 'our', 'to'], dtype='<U11')]

In [32]:
def myTokenizer(document):
    words=tokenizer.tokenize(document.lower())
    words=remove_stopwords(words,sw)
    return words

In [33]:
myTokenizer("The one and only thing is the power")

['one', 'thing', 'power']

In [35]:
cv=cv=CountVectorizer(tokenizer=myTokenizer)

In [36]:
vectorized_corpus=cv.fit_transform(corpus).toarray()

In [37]:
print(vectorized_corpus)

[[1 2 0 0 0 0 2 0 0 1 0 0 1 0 0 1 1 3 0 1 1]
 [0 0 0 1 1 1 0 2 1 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0]]


In [41]:
print(cv.vocabulary_)

{'indian': 12, 'cricket': 6, 'team': 17, 'best': 1, 'world': 20, 'recently': 16, 'proves': 15, 'dominance': 9, 'word': 19, 'australia': 0, 'due': 10, 'corrupted': 4, 'leaders': 13, 'country': 5, 'capital': 3, 'detoriating': 8, 'day': 7, 'movies': 14, 'total': 18, 'bullshit': 2, 'except': 11}


In [40]:
print(len(vectorized_corpus[0]))
print("length is reduced from 31 to 21")

21
length is reduced from 31 to 21


In [42]:
# Test case
test_corpus=["Indian team won the world title"]

In [44]:
test_vect=cv.transform(test_corpus).toarray()
print(test_vect)

[[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1]]


In [53]:
inv_t=cv.inverse_transform(test_vect)
print(inv_t)

[array(['indian', 'team', 'world'], dtype='<U11')]


In [55]:
print(len(inv_t[0]))
print("three words are matched with my train data")

3
three words are matched with my train data


## More ways to create Features
- Unigram
- bigrams
- Trigrams
- n-grams
- TF-IDF Normalization

In [56]:
sent_1=["this is a good movie"]
sent_2=["this is not a good movie"]

In [57]:
docs=[sent_1[0],sent_2[0]]

In [59]:
#Unigram
cv=CountVectorizer()

In [61]:
cv.fit_transform(docs).toarray()

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [62]:
cv.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'not': 3}

In [63]:
#bigrams
cv=CountVectorizer(ngram_range=(2,2))

In [65]:
cv.fit_transform(docs).toarray()

array([[1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1]], dtype=int64)

In [66]:
cv.vocabulary_

{'this is': 4, 'is good': 1, 'good movie': 0, 'is not': 2, 'not good': 3}

In [67]:
#trigrams
cv=CountVectorizer(ngram_range=(3,3))

In [68]:
cv.fit_transform(docs).toarray()

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]], dtype=int64)

In [69]:
cv.vocabulary_

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

In [70]:
#n-grams
cv=CountVectorizer(ngram_range=(1,3))

In [71]:
cv.fit_transform(docs).toarray()

array([[1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]], dtype=int64)

In [72]:
cv.vocabulary_

{'this': 11,
 'is': 2,
 'good': 0,
 'movie': 7,
 'this is': 12,
 'is good': 3,
 'good movie': 1,
 'this is good': 13,
 'is good movie': 4,
 'not': 8,
 'is not': 5,
 'not good': 9,
 'this is not': 14,
 'is not good': 6,
 'not good movie': 10}

## TF-IDF Normalization
- TF = Term frequency - how many times the term is appearing in sentence
- IDF = inverse docement frequency= $log2$(no of documents/no of document containing that term)

In [69]:
corpus=["this is a good movie but it was not very bad movie" ,
       "this is not a good movie",
       "Movie was very bad"]

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
tfidf=TfidfVectorizer()

In [70]:
tfidf.fit_transform(corpus).toarray()

array([[0.27874538, 0.36651667, 0.27874538, 0.27874538, 0.36651667,
        0.4329413 , 0.27874538, 0.27874538, 0.27874538, 0.27874538],
       [0.        , 0.        , 0.46609584, 0.46609584, 0.        ,
        0.361965  , 0.46609584, 0.46609584, 0.        , 0.        ],
       [0.52682017, 0.        , 0.        , 0.        , 0.        ,
        0.40912286, 0.        , 0.        , 0.52682017, 0.52682017]])

In [53]:
tfidf.vocabulary_

{'this': 7,
 'is': 3,
 'good': 2,
 'movie': 5,
 'but': 1,
 'it': 4,
 'was': 9,
 'not': 6,
 'very': 8,
 'bad': 0}

In [79]:
## if we see movie occuring at index 3 has lesser value
## this means higher the occurance lesser the value

### My own TF-IDF Vectorizer

In [17]:
# 1. Calculating term Frequency
# TF=(1+log(number of terms occuring/total no of terms))
from collections import defaultdict,Counter

word_count={}
for doc in range(len(corpus)):
    word_count[doc]=defaultdict(lambda:0)
    word_count[doc]=Counter(corpus[doc].split())
    

In [21]:
word_count[1]

Counter({'this': 1, 'is': 1, 'not': 1, 'a': 1, 'good': 1, 'movie': 1})

In [116]:
import math
tf=math.log2(1+(1/4))
idf=math.log2(len(corpus)/2)+1.0
tf*idf

0.5102439583250714

In [ ]:
import math
tf=[]
for doc in corpus:
    words=doc.split()
    total_words=len(words)
    tf_=[]
    for word in words:
        cal=math.log2(1+(doc))